"""LinkedIn Skill – generates a LinkedIn post draft from a business task.

Called by agent.py when a task is identified as business/marketing.
Self-contained: reads env vars directly, never crashes.

Returns (post_text, status) where status is one of:
  openai_ok        – text generated by OpenAI
  linkedin_fallback – deterministic fallback post
"""

from __future__ import annotations

import os
from datetime import datetime, timezone

try:
    from openai import OpenAI as _OpenAI
except Exception:
    _OpenAI = None  # type: ignore

MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
MAX_CHARS = int(os.getenv("MAX_TASK_CHARS", "6000"))

LINKEDIN_PROMPT_TEMPLATE = """\
You are a professional LinkedIn content writer.
Based on the business task below, write a compelling LinkedIn post (max 200 words).
Use a professional but engaging tone. Include 2-3 relevant hashtags at the end.
Do NOT include any placeholder text like [Company Name] — write generically.

TASK:
{task_text}
"""

# Business/marketing keywords that trigger this skill
BUSINESS_KEYWORDS = {
    "marketing", "linkedin", "campaign", "promote", "post", "brand",
    "social media", "announcement", "launch", "advertisement", "pitch",
    "business", "product", "sales", "lead", "growth", "engagement",
    "content", "strategy", "partnership", "investor", "revenue",
}


def _utc_ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")


def _call_openai(prompt: str) -> tuple[str, str]:
    """Call OpenAI. Returns (response_text, status)."""
    api_key = os.getenv("OPENAI_API_KEY", "").strip()
    if not api_key or _OpenAI is None:
        return ("", "no_api_key")
    try:
        client = _OpenAI(api_key=api_key)
        resp = client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=600,
        )
        text = resp.choices[0].message.content.strip()
        if not text:
            return ("", "openai_empty")
        return (text, "openai_ok")
    except Exception as exc:
        return (f"(OpenAI error: {exc})", "openai_error")


def is_business_task(text: str) -> bool:
    """Return True if the task text contains business/marketing keywords."""
    lower = text.lower()
    return any(kw in lower for kw in BUSINESS_KEYWORDS)


def generate_linkedin_post(task_text: str) -> tuple[str, str]:
    """Generate a LinkedIn post for the given business task.

    Args:
        task_text: Full text of the task.

    Returns:
        (post_text, status) — post copy and status string.
    """
    prompt = LINKEDIN_PROMPT_TEMPLATE.format(task_text=task_text[:MAX_CHARS])
    response, status = _call_openai(prompt)

    if status == "openai_ok" and response:
        return response, status

    fallback = (
        "Exciting update from our team! We've been working on something remarkable "
        "and can't wait to share more details soon. Stay tuned for the big reveal.\n\n"
        "#Innovation #BusinessGrowth #ComingSoon"
    )
    return fallback, "linkedin_fallback"


# Expose prompt template so agent.py can log a snippet
PROMPT_TEMPLATE = LINKEDIN_PROMPT_TEMPLATE
