"""Planning Skill – generates a structured Plan.md for any task.

Called by agent.py as part of the skill-routing loop.
Self-contained: reads env vars directly, never crashes.

Returns (plan_md_content, status) where status is one of:
  openai_ok     – plan generated by OpenAI
  plan_fallback – deterministic fallback (no API key / error)
"""

from __future__ import annotations

import os
from datetime import datetime, timezone

try:
    from openai import OpenAI as _OpenAI
except Exception:
    _OpenAI = None  # type: ignore

MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
MAX_CHARS = int(os.getenv("MAX_TASK_CHARS", "6000"))

PLAN_PROMPT_TEMPLATE = """\
You are a senior AI business analyst. Given the task below, produce a structured Plan.

Output EXACTLY this format:

## 1. Task Analysis
<1-3 sentence analysis of what is being asked>

## 2. Step-by-Step Plan
1. <step>
2. <step>
3. <step>

## 3. Risks & Edge Cases
- <risk or edge case>
- <risk or edge case>

## 4. Output Checklist
- [ ] <deliverable>
- [ ] <deliverable>

Keep it concise and actionable. Do NOT invent facts.

TASK:
{task_text}
"""


def _utc_ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")


def _call_openai(prompt: str) -> tuple[str, str]:
    """Call OpenAI. Returns (response_text, status)."""
    api_key = os.getenv("OPENAI_API_KEY", "").strip()
    if not api_key or _OpenAI is None:
        return ("", "no_api_key")
    try:
        client = _OpenAI(api_key=api_key)
        resp = client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=1200,
        )
        text = resp.choices[0].message.content.strip()
        if not text:
            return ("", "openai_empty")
        return (text, "openai_ok")
    except Exception as exc:
        return (f"(OpenAI error: {exc})", "openai_error")


def generate_plan(task_text: str, task_name: str) -> tuple[str, str]:
    """Generate a structured plan for the given task.

    Args:
        task_text: Full text of the task.
        task_name: Stem of the task filename (used in plan header).

    Returns:
        (plan_md, status) — full markdown content and status string.
    """
    prompt = PLAN_PROMPT_TEMPLATE.format(task_text=task_text[:MAX_CHARS])
    response, status = _call_openai(prompt)

    if status == "openai_ok" and response:
        plan_body = response
    else:
        plan_body = (
            "## 1. Task Analysis\n"
            f"Task '{task_name}' has been received and queued for processing. "
            "AI plan generation is unavailable (OpenAI not configured); "
            "a deterministic fallback plan is provided.\n\n"
            "## 2. Step-by-Step Plan\n"
            "1. Review the task content in Needs_Action.\n"
            "2. Identify the required output or deliverable.\n"
            "3. Execute or delegate the task to the appropriate team member.\n"
            "4. Log completion and move to Done.\n\n"
            "## 3. Risks & Edge Cases\n"
            "- Missing context or incomplete task description.\n"
            "- Dependency on external data not yet available.\n\n"
            "## 4. Output Checklist\n"
            "- [ ] Task reviewed by human approver.\n"
            "- [ ] Action taken and documented.\n"
            "- [ ] Moved to Done after approval.\n"
        )
        status = "plan_fallback"

    plan_md = (
        f"# Plan: {task_name}\n\n"
        f"Generated: {_utc_ts()}\n"
        f"Model: {MODEL}\n"
        f"Status: {status}\n\n"
        "---\n\n"
        f"{plan_body}\n"
    )
    return plan_md, status


# Expose prompt template so agent.py can log a snippet
PROMPT_TEMPLATE = PLAN_PROMPT_TEMPLATE
