"""Summarize Skill – generates a concise AI summary of any task.

Called by agent.py for every task to produce the Pending_Approval output.
Self-contained: reads env vars directly, never crashes.

Returns (summary_text, status) where status is one of:
  openai_ok – summary generated by OpenAI
  fallback  – deterministic fallback summary
"""

from __future__ import annotations

import os
from datetime import datetime, timezone

try:
    from openai import OpenAI as _OpenAI
except Exception:
    _OpenAI = None  # type: ignore

MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
MAX_CHARS = int(os.getenv("MAX_TASK_CHARS", "6000"))

SUMMARY_PROMPT_TEMPLATE = """\
You are an AI employee. Summarize the task clearly in 3-6 bullet points.
Then write a short 'Next actions' section (1-3 bullets).
Keep it concise. Do NOT invent details.

TASK:
{task_text}
"""


def _utc_ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")


def _call_openai(prompt: str) -> tuple[str, str]:
    """Call OpenAI. Returns (response_text, status)."""
    api_key = os.getenv("OPENAI_API_KEY", "").strip()
    if not api_key or _OpenAI is None:
        return ("", "no_api_key")
    try:
        client = _OpenAI(api_key=api_key)
        resp = client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=800,
        )
        text = resp.choices[0].message.content.strip()
        if not text:
            return ("", "openai_empty")
        return (text, "openai_ok")
    except Exception as exc:
        return (f"(OpenAI error: {exc})", "openai_error")


def generate_summary(task_text: str) -> tuple[str, str]:
    """Generate a concise summary for the given task.

    Args:
        task_text: Full text of the task.

    Returns:
        (summary_text, status) — markdown summary and status string.
    """
    prompt = SUMMARY_PROMPT_TEMPLATE.format(task_text=task_text[:MAX_CHARS])
    response, status = _call_openai(prompt)

    if status == "openai_ok" and response:
        return response, status

    fallback = (
        "Silver Agent processed this task (fallback: OpenAI not configured).\n\n"
        "**Summary:**\n"
        "- Task received and logged.\n"
        "- Pending human review and approval.\n\n"
        "**Next actions:**\n"
        "- Review the original task content.\n"
        "- Approve or reject via approve.py.\n"
    )
    return fallback, "fallback"


# Expose prompt template so agent.py can log a snippet
PROMPT_TEMPLATE = SUMMARY_PROMPT_TEMPLATE
